[supervisord]
nodaemon=true
user=root
loglevel = info
pidfile = /tmp/supervisord.pid
logfile = /tmp/supervisord.log

[program:postgresql]
command=/scripts/postgres/wrapper_supervisor.sh
autostart=true
stdout_logfile=/var/log/supervisor/postgres.log
stderr_logfile=/var/log/supervisor/postgres_error.log
user=postgres
stopwaitsecs=60
priority=10

[program:tomcat]
directory=/opt/tomcat
command=/opt/tomcat/bin/wrapper_supervisor.sh
autostart=true
stdout_logfile=/var/log/supervisor/tomcat.log
stderr_logfile=/var/log/supervisor/tomcat_error.log
user=tomcat
stopwaitsecs=60
priority=20

[program:guacd]
directory=/opt/guacamole
command=/opt/guacamole/wrapper_supervisor.sh
autostart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
user=guacd
stopwaitsecs=60
priority=30